# Generated by Django 4.0.3 on 2022-08-19 00:24

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_decripcion_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=helpers.generate_uuid, max_length=9),
        ),
    ]
